//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Recetas = new HashSet<Receta>();
        }
    
        public int cit_idCita { get; set; }
        public int cit_idMedico { get; set; }
        public int cit_idPaciente { get; set; }
        public System.DateTime cit_fechaCreacion { get; set; }
        public System.DateTime cit_fechaCita { get; set; }
        public System.TimeSpan cit_horaCita { get; set; }
        public bool cit_consultaEfectuada { get; set; }
        public bool cit_examenprogramado { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Recetas { get; set; }
    }
}
