//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Examen = new HashSet<Examan>();
        }
    
        public int emp_idEmpleado { get; set; }
        public int emp_idTipoEmpleado { get; set; }
        public string emp_nombre { get; set; }
        public string emp_apellido { get; set; }
        public Nullable<int> emp_idUsuario { get; set; }
        public Nullable<System.DateTime> emp_fechaNacimiento { get; set; }
        public string emp_telefono { get; set; }
        public Nullable<int> emp_idCargo { get; set; }
        public string emp_dui { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual TipoEmpleado TipoEmpleado { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examan> Examen { get; set; }
    }
}
