//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examan
    {
        public int exm_idExamen { get; set; }
        public Nullable<int> exm_idHistorial { get; set; }
        public Nullable<int> exm_idEmpleado { get; set; }
        public Nullable<int> exm_idResultado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Historial Historial { get; set; }
        public virtual Resultado Resultado { get; set; }
    }
}
