//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.Citas = new HashSet<Cita>();
            this.HorarioConsultas = new HashSet<HorarioConsulta>();
            this.MedicoEspecialidads = new HashSet<MedicoEspecialidad>();
        }
    
        public int med_idMedico { get; set; }
        public Nullable<int> med_idSecretaria { get; set; }
        public string med_nombre { get; set; }
        public string med_apellido { get; set; }
        public Nullable<int> med_idUsuario { get; set; }
        public string med_telefono { get; set; }
        public string med_direccion { get; set; }
        public string med_jvpm { get; set; }
        public decimal med_precioConsulta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioConsulta> HorarioConsultas { get; set; }
        public virtual Secretaria Secretaria { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicoEspecialidad> MedicoEspecialidads { get; set; }
    }
}
