//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public int rec_idReceta { get; set; }
        public int rec_idCita { get; set; }
        public string rec_datos { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
